### PR TITLE
Base template

### PR DESCRIPTION
**Pull request by gaouservbf**
HTML 4.01 page is getting constructed, I sync the website each time you do commits so it is upto date, I currently added the base table as im on a phone not on PC, I will make it better, this is no longer a placeholder

### CODE REVIEW

**Comment by bingchris** [comment]
i wont close this, but again please dont make a placeholder and call it a day, copy the content from index and make it work (and look) like index

**Comment by bingchris** [comment]
>  this is no longer a placeholder

it still very much is, its a standard html page with text, and it can be called a placeholder.

**Comment by gaouservbf** [comment]
Stop acting like the main HTML isn't already a placeholder too, I'm basically rebuilding a placeholder come on.

**Comment by bingchris** [comment]
> Stop acting like the main HTML is already a placeholder too, I'm basically rebuilding a placeholder come on.

unless you add the actual content and make it look like the site ill leave this pr unmerged

**Comment by gaouservbf** [comment]
> i wont close this, but again please dont make a placeholder and call it a day, copy the content from index and make it work (and look) like index

I'm not sure what you mean, don't you want a good replica of the main index page? Maybe you want like This is the HTML 4 version labels?

**Comment by bingchris** [comment]
> > i wont close this, but again please dont make a placeholder and call it a day, copy the content from index and make it work (and look) like index
> 
> I'm not sure what you mean, don't you want a good replica of the main index page? Maybe you want like This is the HTML 4 version labels?

i want a replica of the main index page, but right now i am not accepting because it isnt a replica yet

**Comment by gaouservbf** [comment]
> > Stop acting like the main HTML is already a placeholder too, I'm basically rebuilding a placeholder come on.
> 
> unless you add the actual content and make it look like the site ill leave this pr unmerged

When I get back home I will style it, But seriously what content is even there 😑😑

**Comment by bingchris** [comment]
> When I get back home I will style it, But seriously what content is even there 😑😑

right now not much, when i add more content i will merge, in the meantime you can change your repo name to "next-web-html4" or something like that, to clear up confusion, in addition to that, please setup github pages on your fork so you can test it without me having to always merge

**Comment by gaouservbf** [comment]
Yeah, I synced it and I sync it, but merge it when I make the HTML 4.01 look faithful with my premium internet explorer skills

**Comment by gaouservbf** [comment]
> > When I get back home I will style it, But seriously what content is even there 😑😑
> 
> right now not much, when i add more content i will merge, in the meantime you can change your repo name to "next-web-html4" or something like that, to clear up confusion, in addition to that, please setup github pages on your fork so you can test it without me having to always merge

It literally says "forked from" + so is the README markdown saying it, I don't need pages I have Git and Github Desktop already

**Comment by gaouservbf** [comment]
I will not just add HTML 4, I will kinda also make the other stuff faithful because we all know your web design skills

**Comment by bingchris** [comment]
> It literally says "forked from" + so is the README markdown saying it, I don't need pages I have Git and Github Desktop already

fair enough, i reverted that readme tho, makes it more annoying for me to merge

> I will not just add HTML 4, I will kinda also make the other stuff faithful because we all know your web design skills

i do not need that and i wont merge unless i think its fair enough

> Yeah, I synced it and I sync it, but merge it when I make the HTML 4.01 look faithful with my premium internet explorer skills

ok

**Comment by gaouservbf** [comment]
My eyes still hurt after the endermanch styled page so I think most changes will be necessary.

**Comment by bingchris** [comment]
> My eyes still hurt after the endermanch styled page so I think most changes will be necessary.

this is a complete rewrite + complete redesign, so i dont know what you are really talking about

**Comment by gaouservbf** [comment]
Anyways I'm headin' home!

**Comment by bingchris** [comment]
looks good now

**Pull request merged**
